import type { Metadata } from "next";
import { Geist, Geist_Mono, Elms_Sans, Chewy, Noto_Serif_Kannada, Hanken_Grotesk} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar"
import Ribbons from "@/components/Ribbons";
import TransitionProviders from "@/providers/TransitionProviders";
import Footer from "@/components/footer/Footer";


const geist = Geist({
  weight: "400",
  variable: "--font-geist"
})

const noto = Noto_Serif_Kannada({
  weight: "400",
  variable: "--font-noto"
})

const chewy = Chewy({
  weight: "400",
  variable: "--font-chewy"
})
const elms = Elms_Sans({
  weight: "400",
  variable: "--font-elms"
})

const hanken = Hanken_Grotesk({
  weight: "400",
  variable: "--font-hanken"
}
)


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hanken.variable}  antialiased`}
        
      >
        <TransitionProviders>
        <Navbar />
        {children}
        </TransitionProviders>
        <Footer/>
      </body>
    </html>
  );
}
