import type { Metadata } from "next";
import { Geist, Geist_Mono, Elms_Sans, Chewy } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar"
import Ribbons from "@/components/Ribbons";
import TransitionProviders from "@/providers/TransitionProviders";


const chewy =Chewy({
  weight: "400",
  variable: "--font-chewy"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chewy.variable}  antialiased`}
        
      >
        <TransitionProviders>
        <Navbar />
        {children}
        </TransitionProviders>
      </body>
    </html>
  );
}
