import type { Metadata } from "next";
import { Geist, Geist_Mono, Elms_Sans, Chewy, Noto_Serif_Kannada, Hanken_Grotesk} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar"
import Ribbons from "@/components/Ribbons";
import TransitionProviders from "@/providers/TransitionProviders";
import Footer from "@/components/footer/Footer";
import { FORMERR } from "dns";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <TransitionProviders>
        <Navbar />

        {children}
        <Footer/>
        </TransitionProviders>
      </body>
    </html>
  );
}
